/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.jpedidos.pages;

import com.github.jpedidos.components.order.*;
import com.github.jpedidos.components.product.*;
import com.github.jpedidos.components.user.*;
import com.github.jpedidos.controller.UserController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Matka
 */
public class Home extends javax.swing.JFrame {

  /**
   * Creates new form Order
   */
  private orderStore ordStr = new orderStore();
  private UserController userControl = new UserController("mydb");
  private productStore pdStore = new productStore();
  private productRUD pdRUD = new productRUD();
  private userStore user = new userStore();
  private userRUD userR = new userRUD();

  public Home(String usuario) {
    initComponents();

    lbUsername.setText(usuario);

    try {
      lbOffice.setText(userControl.buscarCargo(usuario));

      if (lbOffice.getText().equals("Administrador")) {
        jTab.addTab("Usuários", jUsers);
      } else if (lbOffice.getText().equals("Gerente")) {
        jTab.addTab("Produtos", jProducts);
      }
    } catch (Exception e) {
      System.out.println(e);
    }

    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    this.setTitle("JPedidos");
    this.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jSplitPane1 = new javax.swing.JSplitPane();
    jTab = new javax.swing.JTabbedPane();
    jProducts = new javax.swing.JPanel();
    jToggleButton1 = new javax.swing.JToggleButton();
    jToggleButton2 = new javax.swing.JToggleButton();
    jUsers = new javax.swing.JPanel();
    jOrder = new javax.swing.JPanel();
    lbUsername = new javax.swing.JLabel();
    lbOffice = new javax.swing.JLabel();
    bLogOut = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    jProducts.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jToggleButton1.setText("Cadastrar");
    jToggleButton1.addMouseListener(
      new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
          jToggleButton1MouseClicked(evt);
        }
      }
    );

    jToggleButton2.setText("Cadastrar");
    jToggleButton2.addMouseListener(
      new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
          jToggleButton2MouseClicked(evt);
        }
      }
    );

    bLogOut.addMouseListener(
      new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
          bLogOutMouseClicked(evt);
        }
      }
    );

    javax.swing.GroupLayout jProductsLayout = new javax.swing.GroupLayout(
      jProducts
    );
    jProducts.setLayout(jProductsLayout);
    jProductsLayout.setHorizontalGroup(
      jProductsLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jProductsLayout
            .createSequentialGroup()
            .addGap(855, 855, 855)
            .addComponent(jToggleButton1)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    jProducts.add(pdRUD);
    jProducts.add(pdStore);
    jProductsLayout.setVerticalGroup(
      jProductsLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jProductsLayout
            .createSequentialGroup()
            .addGap(32, 32, 32)
            .addComponent(jToggleButton1)
            .addContainerGap(241, Short.MAX_VALUE)
        )
    );

    jUsers.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );
    jUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    javax.swing.GroupLayout jUsersLayout = new javax.swing.GroupLayout(jUsers);
    jUsers.setLayout(jUsersLayout);
    jUsersLayout.setHorizontalGroup(
      jUsersLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jUsersLayout
            .createSequentialGroup()
            .addGap(855, 855, 855)
            .addComponent(jToggleButton2)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    jUsers.add(user);
    jUsers.add(userR);
    jUsersLayout.setVerticalGroup(
      jUsersLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jUsersLayout
            .createSequentialGroup()
            .addGap(32, 32, 32)
            .addComponent(jToggleButton2)
            .addContainerGap(241, Short.MAX_VALUE)
        )
    );

    jOrder.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    javax.swing.GroupLayout jOrderLayout = new javax.swing.GroupLayout(jOrder);
    jOrder.setLayout(jOrderLayout);
    jOrderLayout.setHorizontalGroup(
      jOrderLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(1800, 1800, 1800)
    );
    ordStr.setLocation(450, 100);
    jOrder.add(ordStr);
    jOrderLayout.setVerticalGroup(
      jOrderLayout
        .createSequentialGroup()
        .addGap(32, 32, 32)
        .addContainerGap(241, Short.MAX_VALUE)
    );

    jTab.addTab("Pedidos", jOrder);

    lbUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    lbUsername.setText("jLabel1");
    lbUsername.setPreferredSize(new java.awt.Dimension(150, 22));

    lbOffice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lbOffice.setForeground(new java.awt.Color(51, 51, 51));
    lbOffice.setText("jLabel1");

    bLogOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    bLogOut.setText("Sair");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jTab)
            .addContainerGap()
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbOffice)
                .addComponent(
                  lbUsername,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addComponent(bLogOut)
            .addGap(32, 32, 32)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(
                      lbUsername,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      21,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      lbOffice,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      17,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bLogOut)
                )
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(jTab)
            .addContainerGap()
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jToggleButton1MouseClicked
    if (jToggleButton1.isSelected()) {
      pdStore.setVisible(true);
      pdRUD.setVisible(false);
    } else {
      pdStore.setVisible(false);
      pdRUD.setVisible(true);
    }
  } //GEN-LAST:event_jToggleButton1MouseClicked

  private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {
    if (jToggleButton2.isSelected()) {
      user.setVisible(true);
      userR.setVisible(false);
    } else {
      user.setVisible(false);
      userR.setVisible(true);
    }
  }

  private void bLogOutMouseClicked(java.awt.event.MouseEvent evt) {
    int dialogResult = JOptionPane.showConfirmDialog(
      null,
      "Would You Like to Save your Previous Note First?",
      "Warning",
      JOptionPane.YES_NO_OPTION
    );

    if (dialogResult == JOptionPane.YES_OPTION) {
      this.dispose();
      new Login();
    }
  }

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bLogOut;
  private javax.swing.JPanel jOrder;
  private javax.swing.JPanel jProducts;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTabbedPane jTab;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JToggleButton jToggleButton2;
  private javax.swing.JPanel jUsers;
  private javax.swing.JLabel lbOffice;
  private javax.swing.JLabel lbUsername;
  // End of variables declaration//GEN-END:variables
}
