/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.jpedidos.components.order;

import com.github.jpedidos.controller.OrderController;
import com.github.jpedidos.controller.ProductController;
import com.github.jpedidos.controller.UserController;
import com.github.jpedidos.model.Connection;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matka
 */
public class orderStore extends javax.swing.JPanel {

  private static DecimalFormat df = new DecimalFormat("0.00");
  private ProductController pdController = new ProductController("mydb");
  private OrderController ordController = new OrderController("mydb");
  private UserController userControl = new UserController("mydb");
  private Connection con, con2;
  private int clickedRow = -1;
  private int clickedRow2 = -1;
  private int status = 1;
  private float valor = 0;

  /**
   * Creates new form store
   */
  public orderStore() {
    initComponents();

    try {
      DefaultTableModel tbModel = (DefaultTableModel) tableProducts.getModel();
      con = pdController.listar("");
      if (con.getRs() != null) {
        tbModel.addRow(
          new Object[] {
            con.getRs().getString("product_name"),
            con.getRs().getString("product_description"),
            con.getRs().getFloat("product_price"),
          }
        );
      }

      while (con.getRs().next()) {
        tbModel.addRow(
          new Object[] {
            con.getRs().getString("product_name"),
            con.getRs().getString("product_description"),
            con.getRs().getFloat("product_price"),
          }
        );
      }
      con.close();
    } catch (Exception e) {
      con.close();
      //TODO: handle exception
    }

    this.setSize(1000, 635);
    this.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tableItens = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    txtClient = new javax.swing.JTextField();
    txtPhone = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    bCloseOrder = new javax.swing.JButton();
    bCancelOrder = new javax.swing.JButton();
    bRemoveItem = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    jStatus = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    tableProducts = new javax.swing.JTable();
    bAddItem = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    txtQtd = new javax.swing.JTextField();
    bListOrders = new javax.swing.JButton();
    bStoreOrder = new javax.swing.JButton();

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );

    tableProducts.addMouseListener(
      new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
          tableProductsMouseClicked(evt);
        }
      }
    );

    bAddItem.addMouseListener(
      new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
          bAddItem(evt);
        }
      }
    );

    bRemoveItem.addMouseListener(
      new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
          bRemoveItem(evt);
        }
      }
    );

    bCloseOrder.addMouseListener(
      new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
          bcloseOrder(evt);
        }
      }
    );

    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
      jPanel2
    );
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );

    jPanel3.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setText("Pedido");

    tableItens.setBorder(
      javax.swing.BorderFactory.createBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );
    tableItens.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    tableItens.setModel(
      new javax.swing.table.DefaultTableModel(
        new Object[][] {},
        new String[] { "Produto", "Quantidade", "Valor" }
      ) {
        public boolean isCellEditable(int row, int column) {
          return false;
        }
      }
    );
    jScrollPane1.setViewportView(tableItens);

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel2.setText("Cliente:");

    txtClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel3.setText("Telefone:");

    bCloseOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    bCloseOrder.setText("Fechar Pedido");

    bCancelOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    bCancelOrder.setText("Cancelar");

    bRemoveItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    bRemoveItem.setText("Remover Item");

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel6.setText("Estado:");

    jStatus.setBackground(new java.awt.Color(255, 255, 255));
    jStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jStatus.setPreferredSize(new java.awt.Dimension(50, 17));
    jStatus.setText("");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
      jPanel3
    );
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel3Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel3Layout
                    .createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(
                      jPanel3Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING,
                          jPanel3Layout
                            .createSequentialGroup()
                            .addComponent(bCancelOrder)
                            .addGap(18, 18, 18)
                            .addComponent(bRemoveItem)
                            .addGap(18, 18, 18)
                            .addComponent(bCloseOrder)
                            .addContainerGap()
                        )
                        .addGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING,
                          jPanel3Layout
                            .createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(180, 180, 180)
                        )
                    )
                )
                .addGroup(
                  jPanel3Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel3Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING,
                          false
                        )
                        .addComponent(
                          jScrollPane1,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          404,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addGroup(
                          jPanel3Layout
                            .createSequentialGroup()
                            .addGroup(
                              jPanel3Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(
                                  txtClient,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  130,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(jLabel2)
                            )
                            .addGap(29, 29, 29)
                            .addGroup(
                              jPanel3Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(jLabel3)
                                .addComponent(
                                  txtPhone,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  130,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE
                            )
                            .addGroup(
                              jPanel3Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(jLabel6)
                                .addComponent(
                                  jStatus,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  60,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                            )
                            .addGap(22, 22, 22)
                        )
                    )
                    .addGap(0, 10, Short.MAX_VALUE)
                )
            )
        )
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          jPanel3Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              68,
              Short.MAX_VALUE
            )
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel3Layout
                    .createSequentialGroup()
                    .addComponent(jLabel2)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      txtClient,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  jPanel3Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel3Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addGroup(
                      jPanel3Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(
                          txtPhone,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jStatus,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                )
            )
            .addGap(18, 18, 18)
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              307,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bCloseOrder)
                .addComponent(bCancelOrder)
                .addComponent(bRemoveItem)
            )
            .addContainerGap()
        )
    );

    jStatus.getAccessibleContext().setAccessibleName("lbStatus");

    jPanel4.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel4.setText("Produtos");

    tableProducts.setBorder(
      javax.swing.BorderFactory.createBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );
    tableProducts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    tableProducts.setModel(
      new javax.swing.table.DefaultTableModel(
        new Object[][] {},
        new String[] { "Nome", "Descrição", "Preço" }
      ) {
        public boolean isCellEditable(int row, int column) {
          return false;
        }
      }
    );
    jScrollPane2.setViewportView(tableProducts);

    bAddItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    bAddItem.setText("Adicionar Item");

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel5.setText("Quantidade:");

    txtQtd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    txtQtd.setText("0");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
      jPanel4
    );
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel4Layout
                    .createSequentialGroup()
                    .addComponent(jLabel4)
                    .addGap(178, 178, 178)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel4Layout
                    .createSequentialGroup()
                    .addComponent(
                      jScrollPane2,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      404,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addContainerGap()
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel4Layout
                    .createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      txtQtd,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      50,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(18, 18, 18)
                    .addComponent(bAddItem)
                    .addContainerGap()
                )
            )
        )
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4)
            .addGap(18, 18, 18)
            .addComponent(
              jScrollPane2,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              0,
              Short.MAX_VALUE
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bAddItem)
                .addComponent(jLabel5)
                .addComponent(
                  txtQtd,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap()
        )
    );

    bListOrders.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    bListOrders.setText("Listar pedidos");

    bStoreOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    bStoreOrder.setText("Efetuar Pedido");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(
                      jPanel4,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(bListOrders)
                )
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              44,
              Short.MAX_VALUE
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(
                      jPanel3,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(28, 28, 28)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(bStoreOrder)
                    .addGap(177, 177, 177)
                )
            )
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bListOrders)
                .addComponent(bStoreOrder)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              33,
              Short.MAX_VALUE
            )
            .addGroup(
              layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addComponent(
                  jPanel3,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jPanel4,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addContainerGap()
        )
    );
  } // </editor-fold>//GEN-END:initComponents

  private void tableProductsMouseClicked(java.awt.event.MouseEvent evt) {
    clickedRow = tableProducts.getSelectedRow();
  }

  private void tableItensMouseClicked(java.awt.event.MouseEvent evt) {
    clickedRow2 = tableItens.getSelectedRow();
  }

  private void bcloseOrder(java.awt.event.MouseEvent evt) {
    DefaultTableModel tbModel = (DefaultTableModel) tableItens.getModel();

    if (txtClient.getText().equals("") || txtPhone.getText().equals("")) {
      JOptionPane.showMessageDialog(
        null,
        "Pedido está vazio!",
        "Aviso",
        JOptionPane.INFORMATION_MESSAGE
      );
    } else {
      valor = 0;
      status = 1;
      JOptionPane.showMessageDialog(
        null,
        "Pedido finalizado!",
        "Aviso",
        JOptionPane.INFORMATION_MESSAGE
      );

      while (tbModel.getRowCount() > 0) {
        tbModel.removeRow(0);
      }

      txtClient.setText("");
      txtPhone.setText("");
      txtQtd.setText("0");
      jStatus.setText("");
      ordController.fecharPedido(ordController.ultimoId());
    }
  }

  private void bRemoveItem(java.awt.event.MouseEvent evt) {
    if (clickedRow2 != tableItens.getRowCount() - 1) {
      DefaultTableModel tbModel = (DefaultTableModel) tableItens.getModel();

      if (clickedRow2 < 0) {
        if (tableItens.getRowCount() == 0) tbModel.removeRow(0);

        try {
          con =
            userControl.listar(
              txtClient.getText(),
              Integer.parseInt(txtPhone.getText())
            );

          if (con.getRs() != null) {
            tbModel.removeRow(clickedRow2);

            df.format(
              valor -=
                Float.parseFloat(tbModel.getValueAt(clickedRow2, 2).toString())
            );

            int productId = pdController.idProduto(
              tableProducts.getValueAt(clickedRow2, 0).toString()
            );
            con2 = pdController.buscarProduto(productId);
            System.out.println("Cheguei aqui");
            int result = Integer.parseInt(
              Float.parseFloat(tbModel.getValueAt(clickedRow2, 2).toString()) /
              con2.getRs().getFloat("product_price") +
              ""
            );

            if (con2.getRs() != null) {
              ordController.removerProduto(
                tableProducts.getValueAt(clickedRow2, 0).toString(),
                result,
                ordController.ultimoId(),
                con.getRs().getInt("user_id")
              );
            }
          }
          con.close();
          con2.close();
        } catch (Exception e) {
          con.close();
          con2.close();
          //TODO: handle exception
        }
      } else {
        JOptionPane.showMessageDialog(
          null,
          "Selecione um item!",
          "Aviso",
          JOptionPane.INFORMATION_MESSAGE
        );
      }
    } else {
      JOptionPane.showMessageDialog(
        null,
        "Total não é um produto!",
        "Aviso",
        JOptionPane.INFORMATION_MESSAGE
      );
    }
  }

  private void bAddItem(java.awt.event.MouseEvent evt) {
    if (!txtClient.getText().equals("") || !txtPhone.getText().equals("")) {
      if (Integer.parseInt(txtQtd.getText()) > 0) {
        if (clickedRow > -1) {
          DefaultTableModel tbModel = (DefaultTableModel) tableItens.getModel();

          if (status == 1) {
            tbModel.insertRow(
              0,
              new Object[] { null, null, "Total: " + valor }
            );
            jStatus.setText("Aberto");
            status = 2;
          }

          try {
            con =
              userControl.listar(
                txtClient.getText(),
                Integer.parseInt(txtPhone.getText())
              );
            if (con.getRs() != null) {
              if (status == 2) {
                ordController.cadastrarPedido(con.getRs().getInt("user_id"));
                status = 3;
              }

              tbModel.insertRow(
                0,
                new Object[] {
                  tableProducts.getValueAt(clickedRow, 0),
                  tableProducts.getValueAt(clickedRow, 1),
                  df.format(
                    Float.parseFloat(
                      tableProducts.getValueAt(clickedRow, 2).toString()
                    ) *
                    Integer.parseInt(txtQtd.getText())
                  ),
                }
              );

              df.format(
                valor +=
                  (
                    Float.parseFloat(
                      tableProducts.getValueAt(clickedRow, 2).toString()
                    ) *
                    Integer.parseInt(txtQtd.getText())
                  )
              );
              tbModel.setValueAt(
                "Total: " + valor,
                tableItens.getRowCount() - 1,
                2
              );
              ordController.adicionarProduto(
                tableProducts.getValueAt(clickedRow, 0).toString(),
                Integer.parseInt(txtQtd.getText()),
                ordController.ultimoId(),
                con.getRs().getInt("user_id")
              );
            }
            con.close();
          } catch (Exception e) {
            // con.close();
            //TODO: handle exception
          }
        } else {
          JOptionPane.showMessageDialog(
            null,
            "Selecione um produto!",
            "Aviso",
            JOptionPane.INFORMATION_MESSAGE
          );
        }
      } else {
        JOptionPane.showMessageDialog(
          null,
          "Insira a quantidade desejada e selecione um produto!",
          "Aviso",
          JOptionPane.INFORMATION_MESSAGE
        );
      }
    } else {
      JOptionPane.showMessageDialog(
        null,
        "Preencha os dados do cliente!",
        "Aviso",
        JOptionPane.INFORMATION_MESSAGE
      );
    }
  }

  private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
    String result;
    limparTextFields();
  }

  private void limparTextFields() {}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bAddItem;
  private javax.swing.JButton bCancelOrder;
  private javax.swing.JButton bCloseOrder;
  private javax.swing.JButton bListOrders;
  private javax.swing.JButton bRemoveItem;
  private javax.swing.JButton bStoreOrder;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel jStatus;
  private javax.swing.JTable tableItens;
  private javax.swing.JTable tableProducts;
  private javax.swing.JTextField txtClient;
  private javax.swing.JTextField txtPhone;
  private javax.swing.JTextField txtQtd;
  // End of variables declaration//GEN-END:variables
}
